FROM php:8.2-apache

# Install required packages and PHP extensions
RUN apt-get update && apt-get install -y \
    zip unzip git curl libzip-dev libpng-dev libonig-dev libxml2-dev \
    && docker-php-ext-install pdo pdo_mysql mbstring zip xml gd \
    && pecl install xdebug-3.2.0 && docker-php-ext-enable xdebug \
    && docker-php-source delete

# Enable Apache rewrite module
RUN a2enmod rewrite

# Copy app code
WORKDIR /var/www/html
COPY . /var/www/html/

# Set permissions
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
CMD ["apache2-foreground"]
